logging:
  level: info

spring:
  http:
    multipart:
      enabled: true
      max-file-size: 3mb
      max-request-size: 20mb
  application:
    name: QA System App
  profiles:
    active: default

server:
  port: 8080




