logging:
  level: 
    root: info

spring:
  http:
    multipart:
      enabled: true
      max-file-size: 3mb
      max-request-size: 20mb
  application:
    name: QA System App
  profiles:
    active: default
  datasource:
    url: jdbc:sqlserver://43.224.136.157:2499;database=qa_system_dev
    username: qa_user
    password: pass@word2
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8080

